name: ⚡ Auto Publisher — Smart Daily Schedule

# ─────────────────────────────────────────────────────────────────
# Runs every hour. The SMART SCHEDULER inside Python decides
# whether it's the right time to post based on:
#   - Best audience times (US/UK/CA research data)
#   - Analytics performance data (updates automatically)
#   - Daily limits (4 shorts, 4 longs/week)
#   - Minimum gaps between posts (no robot patterns)
#
# This single workflow handles EVERYTHING:
#   Shorts (4/day) + Long Videos (4/week) + Analytics update
# ─────────────────────────────────────────────────────────────────

on:
  schedule:
    # Check every hour — smart scheduler decides what to do
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      force_short:
        description: 'Force publish a Short right now'
        required: false
        default: 'false'
      force_long:
        description: 'Force publish a Long video right now'
        required: false
        default: 'false'
      force_analytics:
        description: 'Force analytics update'
        required: false
        default: 'false'

env:
  PYTHONPATH: src

jobs:
  smart-publish:
    name: ⚡ Smart Publisher
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            ffmpeg \
            fonts-dejavu-core \
            fonts-liberation \
            fonts-ubuntu \
            espeak \
            --no-install-recommends
          echo "FFmpeg: $(ffmpeg -version 2>&1 | head -1)"
          echo "Disk: $(df -h / | tail -1)"

      - name: Install Python Dependencies
        run: |
          pip install -q --upgrade pip
          pip install -q -r requirements.txt
          pip install -q gtts

      - name: Setup Directories
        run: |
          mkdir -p data/{questions,published,analytics,dedup}
          mkdir -p assets/{backgrounds,thumbnails}
          mkdir -p output/{shorts,long}

      - name: Restore Data Cache
        uses: actions/cache@v4
        with:
          path: data/
          key: yt-data-auto-${{ github.run_id }}
          restore-keys: yt-data-auto-

      - name: 🧠 Run Smart Publisher
        id: publisher
        env:
          ELEVEN_API_KEY:       ${{ secrets.ELEVEN_API_KEY }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          CAMB_AI_KEY_1:        ${{ secrets.CAMB_AI_KEY_1 }}
          HF_API_TOKEN:         ${{ secrets.HF_API_TOKEN }}
          GEMINI_API_KEY:       ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY:         ${{ secrets.GROQ_API_KEY }}
          OPENROUTER_KEY:       ${{ secrets.OPENROUTER_KEY }}
          PEXELS_API_KEY:       ${{ secrets.PEXELS_API_KEY }}
          PIXABAY_API_KEY:      ${{ secrets.PIXABAY_API_KEY }}
          UNSPLASH_ACCESS_KEY:  ${{ secrets.UNSPLASH_ACCESS_KEY }}
          NASA_API_KEY:         ${{ secrets.NASA_API_KEY }}
          YT_CLIENT_ID_1:       ${{ secrets.YT_CLIENT_ID_1 }}
          YT_CLIENT_SECRET_1:   ${{ secrets.YT_CLIENT_SECRET_1 }}
          YT_REFRESH_TOKEN_1:   ${{ secrets.YT_REFRESH_TOKEN_1 }}
          YT_CLIENT_ID_2:       ${{ secrets.YT_CLIENT_ID_2 }}
          YT_CLIENT_SECRET_2:   ${{ secrets.YT_CLIENT_SECRET_2 }}
          YT_REFRESH_TOKEN_2:   ${{ secrets.YT_REFRESH_TOKEN_2 }}
          YT_CLIENT_ID_3:       ${{ secrets.YT_CLIENT_ID_3 }}
          YT_CLIENT_SECRET_3:   ${{ secrets.YT_CLIENT_SECRET_3 }}
          YT_REFRESH_TOKEN_3:   ${{ secrets.YT_REFRESH_TOKEN_3 }}
          YT_CHANNEL_ID:        ${{ secrets.YT_CHANNEL_ID }}
          YOUTUBE_API_KEY:      ${{ secrets.YOUTUBE_API_KEY }}
          FORCE_SHORT:          ${{ github.event.inputs.force_short }}
          FORCE_LONG:           ${{ github.event.inputs.force_long }}
          FORCE_ANALYTICS:      ${{ github.event.inputs.force_analytics }}
        run: |
          python src/master_runner.py

      - name: Save Data Cache
        uses: actions/cache@v4
        if: always()
        with:
          path: data/
          key: yt-data-auto-${{ github.run_id }}

      - name: Upload Any Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: videos-${{ github.run_number }}
          path: output/
          retention-days: 2
          if-no-files-found: ignore
